[2022-07-03 13:48:31,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task manual__2022-07-03T13:48:27.463893+00:00 [queued]>
[2022-07-03 13:48:32,068] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task manual__2022-07-03T13:48:27.463893+00:00 [queued]>
[2022-07-03 13:48:32,087] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 13:48:32,101] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-03 13:48:32,108] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 13:48:32,179] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2022-07-03 13:48:27.463893+00:00
[2022-07-03 13:48:32,221] {standard_task_runner.py:52} INFO - Started process 1646 to run task
[2022-07-03 13:48:32,278] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'manual__2022-07-03T13:48:27.463893+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpfhat14e_', '--error-file', '/tmp/tmp_eovwplz']
[2022-07-03 13:48:32,283] {standard_task_runner.py:80} INFO - Job 14: Subtask second_task
[2022-07-03 13:48:32,551] {task_command.py:370} INFO - Running <TaskInstance: our_first_dag_v5.second_task manual__2022-07-03T13:48:27.463893+00:00 [running]> on host 677d749653ef
[2022-07-03 13:48:32,804] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-03T13:48:27.463893+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-03T13:48:27.463893+00:00
[2022-07-03 13:48:32,809] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-03 13:48:32,812] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am the second task running after task1']
[2022-07-03 13:48:32,835] {subprocess.py:85} INFO - Output:
[2022-07-03 13:48:32,839] {subprocess.py:92} INFO - hey, I am the second task running after task1
[2022-07-03 13:48:32,842] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-03 13:48:32,917] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220703T134827, start_date=20220703T134831, end_date=20220703T134832
[2022-07-03 13:48:32,981] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-03 13:48:33,073] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
